services:
  # Role Management service
  role-management:
    build:
      context: "/RoleManagment" # Build from RoleManagement folder
    image: role-management:latest # Name of the image
    ports:
      - "8081:8080" # Expose port 8080 of the container on 8081
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/apaica
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sunil
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  # Journal Management service
  journal-management:
    build:
      context: "/JournalManagment" # Build from JournalManagement folder
    image: journal-management:latest # Name of the image
    ports:
      - "8082:8080" # Expose port 8080 of the container on 8082
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/apaica
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sunil
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  # Kafka service
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # Required for client connections
      ZOOKEEPER_TICK_TIME: 2000 # Default tick time for Zookeeper
    ports:
      - "2181:2181"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: apaica
      MYSQL_ROOT_PASSWORD: sunil # Add this line for root password
    ports:
      - "3306:3306"
