# Use Maven image to build the Spring Boot application
FROM maven:3.8.6 AS builder

# Set the working directory to /JournalManagement
WORKDIR /JournalManagment

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy the source code and build the application
COPY src ./src
RUN mvn clean package -DskipTests

# Use lightweight OpenJDK image for running the app
FROM openjdk:11-jdk-slim

# Set the working directory in the runtime container to /JournalManagment
WORKDIR /JournalManagement

# Copy the built JAR file from the build image
COPY --from=build /JournalManagment/target/JournalManagment.jar /JournalManagment/JournalManagment.jar

# Expose the application port
EXPOSE 8080

# Define the command to run the application
ENTRYPOINT ["java", "-jar", "/JournalManagment/JournalManagment.jar"]
